# Generated by Django 5.2.14 on 2026-05-26 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_data', models.JSONField(default=dict)),
                ('parse_status', models.CharField(choices=[('OK', 'OK'), ('FAILED', 'Failed'), ('SUSPICIOUS', 'Suspicious')], default='OK', max_length=20)),
                ('parse_error', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.ingestionjob')),
            ],
        ),
    ]
