# Generated by Django 5.2.14 on 2026-05-26 09:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=20)),
                ('quantity_original', models.DecimalField(decimal_places=4, max_digits=19)),
                ('unit_original', models.CharField(max_length=50)),
                ('quantity_normalized', models.DecimalField(decimal_places=4, max_digits=19)),
                ('unit_normalized', models.CharField(max_length=50)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved')], default='PENDING', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_record', to='records.rawrecord')),
            ],
        ),
    ]
