# Generated by Django 5.2.14 on 2026-05-26 09:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_normalizedrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('INGESTED', 'Ingested'), ('FLAGGED', 'Flagged'), ('EDITED', 'Edited'), ('APPROVED', 'Approved')], max_length=20)),
                ('actor', models.CharField(default='system', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='records.normalizedrecord')),
            ],
        ),
    ]
