# Generated by Django 5.2.14 on 2026-05-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedrecord',
            name='flag_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
